// <auto-generated />
namespace SkyMonitor.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class deviceid_added_to_user : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deviceid_added_to_user));
        
        string IMigrationMetadata.Id
        {
            get { return "201712090800522_deviceid_added_to_user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
