// <auto-generated />
namespace SkyMonitor.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class push_notifications_fields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(push_notifications_fields));
        
        string IMigrationMetadata.Id
        {
            get { return "201712070923481_push_notifications_fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
