// <auto-generated />
namespace SkyMonitor.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class phoneid_renamed_phone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(phoneid_renamed_phone));
        
        string IMigrationMetadata.Id
        {
            get { return "201712082112140_phoneid_renamed_phone"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
